# Generated by Django 2.2.10 on 2020-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_auto_20200508_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
