# Generated by Django 2.2.10 on 2020-05-08 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Number in format: +996555111222', regex='^[+996][0-9]{12,12}$')], verbose_name='Телефон')),
                ('passport', models.CharField(max_length=50, verbose_name='Паспорт')),
                ('position', models.IntegerField(choices=[(1, 'АДМИНИСТРАТОР'), (2, 'БАРМЕН'), (3, 'ГОРНИЧНАЯ')], default=1, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('message_subject', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('question', models.CharField(max_length=1000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('comment', models.CharField(max_length=500, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number_of_beds', models.IntegerField(verbose_name='Количество кроватей')),
                ('family_apartment', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Семейный номер')),
                ('bathroom', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Ванная')),
                ('number_of_places', models.CharField(max_length=250, verbose_name='Размер номера')),
                ('mini_bar', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Мини бар')),
                ('tv', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Телевизор')),
                ('air_conditioning', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Кондиционер')),
                ('wi_fi', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Wi-Fi')),
                ('refrigerator', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Холодильник')),
                ('pets', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Можно с питомцами')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='media/', verbose_name='Фото')),
                ('free', models.BooleanField(default=True, verbose_name='Свободный')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Number in format: +996555111222', regex='^[+996][0-9]{12,12}$')], verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=50, verbose_name='Паспорт')),
                ('mail', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('service', models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=1, verbose_name='Трансфер с аэропорта')),
                ('arrival_date', models.DateField(verbose_name='Дата въезда')),
                ('date_of_departure', models.DateField(verbose_name='Дата выезда')),
                ('price', models.IntegerField(null=True, verbose_name='Цена за номер')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарии')),
                ('reservation', models.BooleanField(default=False, verbose_name='Подтвердить бронь')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.Room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
