# Generated by Django 2.2.10 on 2020-05-07 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('message_subject', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('question', models.CharField(max_length=1000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
    ]
