# Generated by Django 2.2.10 on 2020-04-08 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type_of_number',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_places',
            field=models.CharField(default=1, max_length=250, verbose_name='Количество мест'),
            preserve_default=False,
        ),
    ]
