# Generated by Django 2.2.10 on 2020-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200408_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Свободный'),
        ),
    ]
