# Generated by Django 2.2.10 on 2020-05-10 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200509_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
    ]
