# Generated by Django 2.2.10 on 2020-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200414_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена за номер'),
        ),
    ]
